[package]
name = "bot"
version = "0.1.0"
edition = "2024"

[dependencies]
help_msg = { version = "0.1.0", path = "plugins/help_msg" }
kovi = "0.12.6"
kovi-plugin-cmd = "0.3.0"
markdown = { version = "0.1.0", path = "plugins/markdown" }
msg_rank = { version = "0.1.0", path = "plugins/msg_rank" }
yu_gi_oh = { version = "0.1.0", path = "plugins/yu_gi_oh" }

[workspace]
members = [
    "plugins/help_msg",
    "plugins/markdown",
    "plugins/yu_gi_oh",
    "plugins/utils",
    "plugins/msg_rank",
]

[workspace.dependencies]
help_msg = { path = "plugins/help_msg" }
kovi = "0.12.6"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
reqwest = { version = "0.13", features = ["json", "rustls"] }
utils = { path = "plugins/utils" }
base64 = "0.22"
bytes = "1.4"
askama = "0.15"
moka = { version = "0.12.10", features = ["future"] }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite"] }
futures-util = "0.3"
futures = "0.3"
