[package]
name = "msg_rank"
version = "0.1.0"
edition = "2024"

[dependencies]
utils.workspace = true
kovi.workspace = true
kovi-onebot.workspace = true
serde.workspace = true
anyhow.workspace = true
help_msg.workspace = true
askama.workspace = true
sqlx.workspace = true
base64.workspace = true
jieba-rs = "0.10"
moka.workspace = true
reqwest = { workspace = true }
sha2 = "0.11"
hmac = "0.13"
chrono = "0.4"
rand = "0.10"
bytes.workspace = true
futures.workspace = true
tracing.workspace = true
playwright-rs.workspace = true
serde_json = "1.0"
