[package]
name = "msg_rank"
version = "0.1.0"
edition = "2024"

[dependencies]
utils = { workspace = true, features = ["screenshot"] }
arc-swap.workspace = true
kovi.workspace = true
kovi-onebot.workspace = true
serde.workspace = true
anyhow.workspace = true
askama.workspace = true
sqlx.workspace = true
base64.workspace = true
jieba-rs.workspace = true
moka.workspace = true
reqwest.workspace = true
sha2.workspace = true
hmac.workspace = true
rand.workspace = true
bytes.workspace = true
tracing.workspace = true
image.workspace = true
wordcloud.workspace = true
