[package]
name = "bilibili"
version = "0.1.0"
edition = "2024"

[dependencies]
kovi.workspace = true
utils.workspace = true
serde.workspace = true
reqwest.workspace = true
anyhow.workspace = true
bytes.workspace = true
help_msg.workspace = true
regex = "1.12.3"
base64.workspace = true
moka.workspace = true
tracing.workspace = true
arc-swap.workspace = true
thiserror.workspace = true
