[package]
name = "utils"
version = "0.1.0"
edition = "2024"

[dependencies]
pulldown-cmark.workspace = true
kovi.workspace = true
anyhow.workspace = true
askama.workspace = true
chromiumoxide = "0.9"
futures.workspace = true
tracing.workspace = true
arc-swap.workspace = true
reqwest.workspace = true
ammonia = "4"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
